apply plugin: 'war'

dependencies {
    compileOnly project(':java:timebase:commons')
    compileOnly ('com.epam.deltix:timebase-util')

//    compileOnly 'java:tools'
    compileOnly 'com.sun.activation:javax.activation'
    compileOnly 'org.apache.tomcat.embed:tomcat-embed-jasper' // Tomcat JSP support
    compileOnly 'org.apache.tomcat.embed:tomcat-embed-logging-juli' // Tomcat Logging

    compileOnly 'javax.servlet.jsp.jstl:jstl-api'; // JSTL Support
    compileOnly 'org.apache.taglibs:taglibs-standard-impl' // Tomcat JSTL Support
    compileOnly 'com.epam.deltix:gflog-api'
}

def webappDir = file('src/main/webapp')
def generatedJsps = file("$buildDir/generated-jsp")

def webappXml = file("$webappDir/WEB-INF/web.xml")
def generatedXml = file("$generatedJsps/generated_web.xml")
def mergedXml = file("$generatedJsps/web.xml")

tasks.register('compileJsps') {
    description = 'Build java classes from jsp webapp'

    doFirst {
        generatedJsps.deleteDir() // Delete existing files to perform a clean build
        generatedJsps.mkdirs()
        mergedXml.createNewFile()
    }

    // Input
    def compileClasspath = configurations.compileClasspath.asPath
    doLast {
        ant.taskdef(classname: 'org.apache.jasper.JspC', name: 'jasper', classpath: compileClasspath)
        ant.jasper(validateXml: false, uriroot: webappDir, webXmlFragment: generatedXml, outputDir: generatedJsps)
    }

    doLast {
        // Merge the generated XML with the original
        mergedXml.text = webappXml.text.replaceFirst('(?s)(<web-app.*?>)', '$1' + generatedXml.text)
    }

    inputs.file(webappXml).withPropertyName("webappXml")
    inputs.dir(webappDir)
            .withPropertyName("webappDir")

    outputs.file(generatedXml)
            .withPropertyName("generatedXml")
    outputs.file(mergedXml)
            .withPropertyName("mergedXml")
    outputs.dir(generatedJsps)
            .withPropertyName("generatedJsps")
}

tasks.named('war') {
    dependsOn 'compileJsps', 'jar'
    duplicatesStrategy = "EXCLUDE"
    webXml = mergedXml
}

sourceSets.main.java.srcDirs generatedJsps
tasks.named('compileJava') {
    dependsOn 'compileJsps'
}

tasks.named('processResources') {
    dependsOn 'compileJsps'
}

tasks.named('jar') {
    duplicatesStrategy = "WARN"
}