#!/bin/sh
### BEGIN INIT INFO
# Provides: ${process}
# Default-Start: ${level.start}
# Default-Stop: ${level.stop}
# Required-Start: ${required.start}
# Required-Stop: ${required.stop}
# Short-Description: ${process.description}
# Description: ${process.description.long}
### END INIT INFO


start() {
    echo -n "Starting ${process.name}..."
    export DELTIX_HOME=${deltix.home}
    ${mono.cmd} -l:${process.pid.file} ${process.mono.options}
}

stop() {
    echo -n "Shutting down ${process.name}..."
    kill `cat ${process.pid.file}`
    rm ${process.pid.file}
}

restart() {
    echo -n "Restarting ${process.name}:"
    stop
    start
}

status() {
    export DELTIX_HOME=${deltix.home}
    ${java.cmd} ${process.java.status.options}
}

case "$1" in
    start)
        start
            ;;
    stop)
        stop
            ;;
    restart)
        restart
            ;;
    status)
        status
            ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac
exit $?